### ISSUE TITLE
Start Building About Page

### ISSUE THREAD

**Issue by mwilkins74** [mwkwsd/sensensomething#114]
***Waiting on Design. ***

Will eventually need a config page that will allow Kurt to update.

**Comment by kmdunn5** [comment]
Looks like there are some designs on the UI Round 2 page. @ChuckBTaylor are we good to build that out?

**Comment by mwilkins74** [comment]
For future use:

https://www.figma.com/file/Sw7uUdfgvrYhLAyIqU3ERK/SensenSomething?type=design&node-id=1852-2626&mode=design&t=mpvrsxCygZUlEkOY-4

**Comment by ChuckBTaylor** [comment]
Initial About Page is built. Closing issue. Will create a new one when needed
