### ISSUE TITLE
Nav menu needs current location

### ISSUE THREAD

**Issue by kmdunn5** [mwkwsd/sensensomething#120]
Designs show us telling the user the current location. `useLocation()` should be able to help here.

<img width="179" alt="Screenshot 2024-03-05 at 10 41 54 PM" src="https://github.com/mwkwsd/sensensomething/assets/77169232/c33f7ae7-b8d3-4bce-8ff4-fc3bc48469f3">

**Comment by ChuckBTaylor** [comment]
Done
