### ISSUE TITLE
Implement limited scrolls

### ISSUE THREAD

**Issue by kmdunn5** [mwkwsd/sensensomething#122]
Our designs have the following two buttons at the bottom of the genre/roles index. We should implement those so Kurt can get some work!

<img width="361" alt="Screenshot 2024-03-05 at 10 47 21 PM" src="https://github.com/mwkwsd/sensensomething/assets/77169232/51e1a0d0-562b-42e8-9ace-b1bed1a22488">

**Comment by ChuckBTaylor** [comment]
Seems done to me
