### ISSUE TITLE
Fix background color

### ISSUE THREAD

**Issue by ChuckBTaylor** [mwkwsd/sensensomething#137]
Tough to see, but on the video-list pages, the header has a different background color

![image](https://github.com/mwkwsd/sensensomething/assets/29478554/4585d159-4255-4537-8787-38ee631dfd88)

We want `background: #0C0D0D;`, but I think we're seeing something else

Actually, I see it on the video titles as well:

![image](https://github.com/mwkwsd/sensensomething/assets/29478554/9bfc7000-47ce-47ed-a486-b2281d93fe76)

**Comment by mwilkins74** [comment]
We want `background: #0C0D0D;` for the header?
On Figma when you click on the Header it shows the color we already have: `#191B1B`.

**Comment by mwilkins74** [comment]
<img width="1160" alt="Screen Shot 2024-03-29 at 1 22 55 PM" src="https://github.com/mwkwsd/sensensomething/assets/102488171/eb51cff5-0b0e-4d11-9e61-10c4025125f1">

**Comment by mwilkins74** [comment]
Current Header with the change to `background: #0C0D0D;`

<img width="370" alt="Screen Shot 2024-03-29 at 1 24 31 PM" src="https://github.com/mwkwsd/sensensomething/assets/102488171/a53128b5-bd5a-43f8-98c3-cc4c25a5f610">

**Comment by ChuckBTaylor** [comment]
It's not the KURT SENSENBRENNER and burger menu color that's wrong. It's the... Oh I see.

The black bars on the top and bottom of each still are a darker color than the background of the page. So it looks like we've got a bunch of different colors.

**Comment by mwilkins74** [comment]
According to the Figma the colors are as below:

Header: #191B1B
Body: #0C0D0D
Footer: #191B1B

Which is what the colors are currently - verified through a colorpicker browser extenstion.
