### ISSUE TITLE
Where am I going??

### ISSUE THREAD

**Issue by ChuckBTaylor** [mwkwsd/sensensomething#138]
When on any(?) page except the home page, I am able to scroll beyond the footer. How does that even happen?

![image](https://github.com/mwkwsd/sensensomething/assets/29478554/d9f3e1f4-ebaf-433d-b2cc-7aa581982682)

**Comment by ChuckBTaylor** [comment]
I think it's leaving space for the videos that aren't in view.  After I load all the videos on a page, it behaves as expected.

**Comment by mwilkins74** [comment]
The scrolling is also "bouncing" above the header as well. 

<img width="383" alt="Screen Shot 2024-03-29 at 4 35 09 PM" src="https://github.com/mwkwsd/sensensomething/assets/102488171/f10ddf68-7b76-4d69-8843-3151f01fd556">

**Comment by mwilkins74** [comment]
This is the functionality I am seeing. The "bounce" I am referring to. 
You can see it happen above the Header as well as below the Footer. Loading all of the Videos doesn't change anything. 
Recording of what I am seeing:
https://github.com/mwkwsd/sensensomething/assets/102488171/6008dd8f-f0bf-4cdc-96d1-37146717a89c

In `KurtApp.tsx` I tried replacing the JSX fragment with a div and applying `overflowY: 'hidden'`, which didn't do anything. 
I found this MDN [article](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior) that seemed to have the solution we needed, but this also did nothing. Still "bouncing" at the top and bottom of the page. 

I tried building `overscroll-behavior: none` into the theme file as well as setting it directly in `KurtApp.tsx`. No luck. 

So looking to clarify what exactly you're seeing or how it happened for you?
And suggestions for what to try next?

**Comment by ChuckBTaylor** [comment]
Not sure. Behavior seems gone now... I can't replicate. Will close issue
