### ISSUE TITLE
Setup routing

### ISSUE THREAD

**Issue by kmdunn5** [mwkwsd/sensensomething#8]
Get react router to work with some of our pages

**Comment by ChuckBTaylor** [comment]
Thoughts... 

* `/` - landing page
  (recent work, contact me, & genre selection)
  *  `/video-list?[role={role}]&[genre={genre}]`
     video-list page filtered by genre or (/ and?) role
  *  `/video-list/series` (or just /`series` ?)
     Specific page for series (which will likely have its own layout
  * `/video-list/animation` (or just `/animation`)
     Page for animation

**Comment by mwilkins74** [comment]
Closed by #15
