### ISSUE TITLE
Kurt wants a video modal

### ISSUE THREAD

**Issue by ChuckBTaylor** [mwkwsd/sensensomething#92]
If you go to Kurt's [current website](https://www.sensensomething.com/work), the video list he has there is not in-line videos.  It's clickable photos. When clicked, a modal opens and the rest of the page gets darker. Then the `<iframe>` opens and plays the selected video.

This issue to create the modal component. This component should open on click of any video, darken the rest of the page, and auto-play the selected video.

**Comment by mwilkins74** [comment]
We're doing a text "button" to trigger the modal vs the arrow in the mockups?

**Comment by ChuckBTaylor** [comment]
The arrow? Not sure I understand the question.

**Comment by mwkwsd** [comment]
Talking about these arrows from the mockups.
