### ISSUE TITLE
No in-line videos

### ISSUE THREAD

**Issue by ChuckBTaylor** [mwkwsd/sensensomething#93]
As mentioned in issue #92, we no longer want in-line videos.

* Update the `IVideoInfo` interface with a `imageIUrl` prop.  That image should be shown on all the pages where we are now showing in-line videos.
* Add a play button to hover over the image
* When the image is clicked, open the mdoal created in #92

**Comment by mwilkins74** [comment]
Started poking at this issue. 

Discovered that you can take a YouTube URL:
https://www.youtube.com/embed/_nBMbcRtteU?si=eAZ04KEZC01r211L

And turn it into a URL that looks like this in order to get the thumbnail:
https://img.youtube.com/vi/_nBMbcRtteU/0.jpg

So I then created a `util` file called `videoThumbnail` and worked some regex into it:

```
export function videoThumbnail(url: string): string {
  const youtubeRegex = /(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})/;

  const youtubeMatch = url.match(youtubeRegex);

  if (youtubeMatch && youtubeMatch[1]) {
    return `https://img.youtube.com/vi/${youtubeMatch[1]}/0.jpg`;
  }

  return "";
}
```

This works for YouTube, but am still trying to figure out the Vimeo side of it. 

Additionally, is there a way to implement something like this without having to add lines of code to every file containing YouTube and Vimeo embed URLs?

**Comment by ChuckBTaylor** [comment]
>Discovered that you can take a YouTube URL:
https://www.youtube.com/embed/_nBMbcRtteU?si=eAZ04KEZC01r211L

>And turn it into a URL that looks like this in order to get the thumbnail:
https://img.youtube.com/vi/_nBMbcRtteU/0.jpg

Yup. Definitely a good idea

>So I then created a util file called videoThumbnail and worked some regex into it:

So you're extracting the videoId from the URL and then applying it to the thumbnail URL? Nice! I assume you found that it works for Vimeo as well?

>Also, is there a way to implement something like this without having to add lines of code to every file containing YouTube and Vimeo embed URLs?

Oh ya. I would not add this to our "database".

>Not sure if this is the best approach?

I think we definitely want to have this. HOWEVER, I think it's the fallback approach.

Kurt would like the option to control exactly what photo is shown on his website, not have it controlled by whoever owns the videos.  So for any given video, he wants to be able to upload a photo and show that photo.  I'd say that if we don't have a photo for a video, then we can reach out to YT/Vimeo to get the thumbnail.

**Comment by mwilkins74** [comment]
Yes, I tested both regex functions and both work to translate the Youtube and Vimeo video embed links into thumbnail URLs.

**Comment by ChuckBTaylor** [comment]
Only if we don't have a photo. I'm thinking that `IVideoInfo` will look like: 

```typescript
export interface IVideoInfo {
  readonly url: string
  readonly title: string
  readonly thumbnailPath?: string // new key
  readonly description?: string
  readonly clientName?: string
  readonly roles: readonly Role[]
  readonly genres: readonly Genre[]
}
```

Then when we are rendering that video cards, we'll have something like:

```typescript
const image = videoData.thumbnailPath ? videoData.thumbnailPath : queryForVideoThumbail(videoData.url)

// ...

function queryForVideoThumbail(videoUrl: string){
  const videoThumbnailUrl = '' //  Mark's fancy code to get video url
  return get(videoThumbnailUrl)
}
```
